###
POST http://localhost:3100/api/v1/users/new-user HTTP/1.1
Content-Type: application/json

{
    "firstname": "test1",
    "lastname": "test",
    "email": "test@test22.com",
    "telephone_number": "30112312322",
    "current_password": "user1232"
}

###
GET http://localhost:3100/api/v1/users HTTP/1.1
###
GET http://localhost:3100/api/v1/users/6515d41808851311b9f957ec HTTP/1.1
###
PATCH  http://localhost:3100/api/v1/users/6511f37374aa938417bd7f5d HTTP/1.1
Content-Type: application/json

{
    "firstname": "Test Uno v1",
    "lastname": "Test Uno "
}
###
PUT   http://localhost:3100/api/v1/users/6511f37374aa938417bd7f5d HTTP/1.1
Content-Type: application/json

{
    "firstname": "Perro",
    "lastname": "Perez "
}

###
DELETE http://localhost:3100/api/v1/users/65408a2cc34a783d113a93aa HTTP/1.1

